---
title: "rq_fit"
author: "Yiming Li"
output: html_document
---

```{r}
library(SparseM)
library(quantreg)
library(tidyverse)
library(conquer)
```


```{r}
## size for different setting
NX = c(rep(200, 6), rep(400, 6), rep(600, 6))
NZ = c(rep(c(30, 30, 60, 60, 90, 90), 3))
TAU = rep(c(0.25, 0.5), 9)
```


## bias computing
```{r, message=F}
for (i in 1:18) {
  nx = NX[i]
  nz = NZ[i]
  tau = TAU[i]
  for (j in 1:10) {
    name = ## directory of simulated data from MATLAB
    col = 5001 + nz 
    dat = as.matrix(read_csv(name, col_names = F), ncol = col)
    Y = dat[, 1]
    Z = dat[, 2:(nz + 1)]
    X = dat[, (nz + 2):col]
    for (k in 1:5000) {
      X1 = cbind(1, Z, X[, k])
      res1 = rq.fit.fnb(X1, Y, tau = tau)$coefficients
      ## other rq.fit can be applied 
      
      
      ## conquer naturally includes intercept
      X2 = cbind(Z, X[, k])
      res2 = conquer(X2, Y, tau = tau, kernel = "Gaussian")$coeff
      ## try with default Gaussian kernel
      
      diff1 = mean(abs(res1 - res2)/abs(res1)) ## relative bias
      diff2 = mean(abs(res1 - res2)) ## bias
    }
  }
}
```


## time computing
```{r, message=F}
for (i in 1:18) {
  nx = NX[i]
  nz = NZ[i]
  tau = TAU[i]
  for (j in 1:10) {
    name = ## directory of simulated data from MATLAB
    col = 5001 + nz 
    dat = as.matrix(read_csv(name, col_names = F), ncol = col)
    Y = dat[, 1]
    Z = dat[, 2:(nz + 1)]
    X = dat[, (nz + 2):col]
    start =  as.numeric(Sys.time())
    for (k in 1:5000) {      
      #X1 = cbind(1, Z, X[, k])
      #res1 = rq.fit.fnb(X1, Y, tau = tau)$coefficients

      
      X2 = cbind(Z, X[, k])
      res2 = conquer(X2, Y, tau = tau, kernel = "Gaussian")$coeff
    }
    end =  as.numeric(Sys.time())
    time = rbind(time, end - start)

  }
}
```
